//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AplikacijaZaEvidencijuRadnihSati.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string Datum {
            get {
                return ResourceManager.GetString("Datum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evidencija radnog vremena.
        /// </summary>
        public static string Evidencija {
            get {
                return ResourceManager.GetString("Evidencija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukoliko želite uključiti ili isključiti automatski mjerač vremena, kliknite na plavi gumb. Dostupna su i dodatna polja za ručni unos radnih sati i prekovremenih sati..
        /// </summary>
        public static string EvidencijaTxt {
            get {
                return ResourceManager.GetString("EvidencijaTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentar.
        /// </summary>
        public static string Komentar {
            get {
                return ResourceManager.GetString("Komentar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evidencija.
        /// </summary>
        public static string Link1 {
            get {
                return ResourceManager.GetString("Link1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predani izvještaji.
        /// </summary>
        public static string Link2 {
            get {
                return ResourceManager.GetString("Link2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string Link3 {
            get {
                return ResourceManager.GetString("Link3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite datum....
        /// </summary>
        public static string OdaberiteDatum {
            get {
                return ResourceManager.GetString("OdaberiteDatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odustani.
        /// </summary>
        public static string Odustani {
            get {
                return ResourceManager.GetString("Odustani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozdrav.
        /// </summary>
        public static string Pozdrav {
            get {
                return ResourceManager.GetString("Pozdrav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predaj.
        /// </summary>
        public static string Predaj {
            get {
                return ResourceManager.GetString("Predaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prekovremeni sati.
        /// </summary>
        public static string PrekovremeniSati {
            get {
                return ResourceManager.GetString("PrekovremeniSati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekt.
        /// </summary>
        public static string Projekt {
            get {
                return ResourceManager.GetString("Projekt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radni sati.
        /// </summary>
        public static string RadniSati {
            get {
                return ResourceManager.GetString("RadniSati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spremi.
        /// </summary>
        public static string Spremi {
            get {
                return ResourceManager.GetString("Spremi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mjerač vremena.
        /// </summary>
        public static string Timer {
            get {
                return ResourceManager.GetString("Timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trenutno je.
        /// </summary>
        public static string TrenutnoJe {
            get {
                return ResourceManager.GetString("TrenutnoJe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukupno.
        /// </summary>
        public static string Ukupno {
            get {
                return ResourceManager.GetString("Ukupno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrijeme.
        /// </summary>
        public static string Vrijeme {
            get {
                return ResourceManager.GetString("Vrijeme", resourceCulture);
            }
        }
    }
}
